name = technic
depends = default, pipeworks, basic_materials, technic_worldgen
optional_depends = """
bucket, screwdriver, dye,
mesecons, mesecons_mvps, digiline_remote,
unified_inventory, craftguide, i3
"""
